// lib/models/food/food_recommendations.dart
import 'package:flutter/material.dart';

class FoodRecommendation {
  final String name;
  final int kcal;
  final String desc;
  final IconData icon;
  final String type; // morning / afternoon / evening / snack / any

  FoodRecommendation({
    required this.name,
    required this.kcal,
    required this.desc,
    required this.icon,
    required this.type,
  });
}

final List<FoodRecommendation> allFoods = [
  // --- EXISTING MORNING FOODS (001-005) ---
  FoodRecommendation(
    name: 'Oatmeal',
    kcal: 280,
    desc: 'Filling breakfast rich in fiber',
    icon: Icons.breakfast_dining,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Greek Yogurt',
    kcal: 150,
    desc: 'Protein-rich dairy for a light start',
    icon: Icons.local_cafe,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Scrambled Eggs',
    kcal: 200,
    desc: 'High-protein breakfast option',
    icon: Icons.egg,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Avocado Toast',
    kcal: 250,
    desc: 'Healthy fats and whole grain',
    icon: Icons.grass,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Fruit Bowl',
    kcal: 180,
    desc: 'Vitamins and antioxidants',
    icon: Icons.apple,
    type: 'morning',
  ),

  // --- NEW MORNING FOODS (006-030) ---
  FoodRecommendation(
    name: 'Smoothie (Berry)',
    kcal: 190,
    desc: 'Quick and nutritious blend',
    icon: Icons.local_drink,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Whole Wheat Pancakes',
    kcal: 320,
    desc: 'Better choice than white flour',
    icon: Icons.bakery_dining,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Cottage Cheese & Peaches',
    kcal: 210,
    desc: 'Low-fat protein with fruit',
    icon: Icons.breakfast_dining,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Breakfast Burrito',
    kcal: 380,
    desc: 'Hearty mix of eggs, beans, and veggies',
    icon: Icons.fastfood,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Hard-Boiled Eggs',
    kcal: 140,
    desc: 'Simple, pure protein source',
    icon: Icons.egg_alt,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Chia Seed Pudding',
    kcal: 220,
    desc: 'High fiber, omega-3 rich',
    icon: Icons.grain,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Tofu Scramble',
    kcal: 240,
    desc: 'Vegan, protein-packed alternative',
    icon: Icons.eco,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'English Muffin w/ Jam',
    kcal: 250,
    desc: 'Simple carb-based energy boost',
    icon: Icons.local_cafe,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Protein Shake',
    kcal: 180,
    desc: 'Fast muscle repair and fuel',
    icon: Icons.fitness_center,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Waffles (Whole Grain)',
    kcal: 300,
    desc: 'Crispy and complex carbohydrates',
    icon: Icons.bakery_dining,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Bagel with Cream Cheese',
    kcal: 350,
    desc: 'Classic, satisfying breakfast',
    icon: Icons.bakery_dining,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Breakfast Cereal (High Fiber)',
    kcal: 200,
    desc: 'Quick and fiber-focused',
    icon: Icons.breakfast_dining,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Potato and Veggie Hash',
    kcal: 280,
    desc: 'Warm and comforting meal',
    icon: Icons.dinner_dining,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Peanut Butter Toast',
    kcal: 310,
    desc: 'High in fat and protein',
    icon: Icons.breakfast_dining,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Kefir Smoothie',
    kcal: 160,
    desc: 'Probiotic-rich morning drink',
    icon: Icons.local_drink,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Muesli',
    kcal: 260,
    desc: 'Oats, nuts, and seeds mix',
    icon: Icons.grain,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Sausage and Egg McMuffin',
    kcal: 350,
    desc: 'Fast food option with protein',
    icon: Icons.fastfood,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Breakfast Quiche',
    kcal: 290,
    desc: 'Savory egg and crust dish',
    icon: Icons.pie_chart,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Ricotta with Honey',
    kcal: 220,
    desc: 'Creamy and sweet protein',
    icon: Icons.wb_sunny,
    type: 'morning',
  ),
  FoodRecommendation(
    name: 'Pumpernickel Toast w/ Butter',
    kcal: 240,
    desc: 'Dark rye bread with fat',
    icon: Icons.bakery_dining,
    type: 'morning',
  ),


  // --- EXISTING AFTERNOON FOODS (031-035) ---
  FoodRecommendation(
    name: 'Grilled Chicken Wrap',
    kcal: 420,
    desc: 'Lean protein lunch option',
    icon: Icons.lunch_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Quinoa Salad',
    kcal: 350,
    desc: 'High in fiber and plant protein',
    icon: Icons.eco,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Turkey Sandwich',
    kcal: 400,
    desc: 'Balanced protein and carbs',
    icon: Icons.fastfood,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Veggie Soup',
    kcal: 220,
    desc: 'Light and warm meal',
    icon: Icons.soup_kitchen,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Brown Rice & Tofu',
    kcal: 380,
    desc: 'Plant-based balanced meal',
    icon: Icons.set_meal,
    type: 'afternoon',
  ),

  // --- NEW AFTERNOON FOODS (036-070) ---
  FoodRecommendation(
    name: 'Lentil Soup',
    kcal: 310,
    desc: 'Filling and iron-rich',
    icon: Icons.soup_kitchen,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Chicken Caesar Salad',
    kcal: 450,
    desc: 'Classic, savory salad',
    icon: Icons.local_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Tuna Melt Sandwich',
    kcal: 480,
    desc: 'Comfort food with omega-3',
    icon: Icons.fastfood,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Black Bean Burger',
    kcal: 390,
    desc: 'Vegetarian burger option',
    icon: Icons.bug_report,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Pasta Salad (Pesto)',
    kcal: 410,
    desc: 'Carb-heavy, flavorful lunch',
    icon: Icons.ramen_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Pork Chop & Apple Sauce',
    kcal: 460,
    desc: 'Traditional hearty dish',
    icon: Icons.dinner_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Bunless Cheeseburger',
    kcal: 330,
    desc: 'Low-carb protein focus',
    icon: Icons.no_food,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Shrimp and Grits',
    kcal: 470,
    desc: 'Southern comfort meal',
    icon: Icons.lunch_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Spicy Chicken Wings (6pc)',
    kcal: 500,
    desc: 'High fat, high protein indulgence',
    icon: Icons.local_bar,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Beef & Broccoli Stir-Fry',
    kcal: 440,
    desc: 'Protein and vitamin blend',
    icon: Icons.set_meal,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Falafel Wrap',
    kcal: 390,
    desc: 'Mediterranean plant-based lunch',
    icon: Icons.set_meal,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Minestrone Soup',
    kcal: 280,
    desc: 'Italian vegetable and pasta soup',
    icon: Icons.soup_kitchen,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Cobb Salad',
    kcal: 480,
    desc: 'Rich salad with avocado, eggs, and bacon',
    icon: Icons.local_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Philly Cheesesteak',
    kcal: 550,
    desc: 'Heavy, high-calorie sandwich',
    icon: Icons.fastfood,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Sushi Rolls (California)',
    kcal: 320,
    desc: 'Light and fresh seafood option',
    icon: Icons.set_meal,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Taco Salad',
    kcal: 430,
    desc: 'Customizable, savory salad',
    icon: Icons.local_bar,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Shepherd\'s Pie',
    kcal: 490,
    desc: 'Hearty baked meat and potato dish',
    icon: Icons.dinner_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Soba Noodles with Veggies',
    kcal: 360,
    desc: 'Japanese buckwheat noodles',
    icon: Icons.ramen_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'BBQ Pulled Pork Sandwich',
    kcal: 510,
    desc: 'Smoky, sweet, and rich',
    icon: Icons.fastfood,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Caprese Salad',
    kcal: 300,
    desc: 'Tomato, mozzarella, and basil',
    icon: Icons.grass,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Chicken and Waffles',
    kcal: 600,
    desc: 'Sweet and savory fried favorite',
    icon: Icons.dinner_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Beetroot & Goat Cheese Salad',
    kcal: 340,
    desc: 'Earthy and tangy flavors',
    icon: Icons.eco,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Pad Thai (Vegetarian)',
    kcal: 450,
    desc: 'Sweet and sour noodle dish',
    icon: Icons.restaurant_menu,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Samosas (2 pieces)',
    kcal: 300,
    desc: 'Fried savory pastry',
    icon: Icons.food_bank,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Reuben Sandwich',
    kcal: 580,
    desc: 'High-fat corned beef deli sandwich',
    icon: Icons.fastfood,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Pho (Beef Noodle Soup)',
    kcal: 400,
    desc: 'Vietnamese aromatic soup',
    icon: Icons.ramen_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Chicken Pot Pie',
    kcal: 520,
    desc: 'Creamy filling with flaky crust',
    icon: Icons.pie_chart,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Muffuletta Sandwich',
    kcal: 650,
    desc: 'New Orleans specialty, high-calorie',
    icon: Icons.fastfood,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Cabbage Rolls',
    kcal: 320,
    desc: 'Meat and rice in cabbage leaves',
    icon: Icons.dinner_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Spinach and Feta Omelette',
    kcal: 260,
    desc: 'Protein-packed and savory',
    icon: Icons.egg,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Gazpacho (Cold Soup)',
    kcal: 180,
    desc: 'Refreshing, low-calorie tomato soup',
    icon: Icons.soup_kitchen,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Cuban Sandwich',
    kcal: 490,
    desc: 'Ham, pork, and cheese on bread',
    icon: Icons.fastfood,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Chicken Tikka Masala (with Rice)',
    kcal: 500,
    desc: 'Indian classic, rich and creamy',
    icon: Icons.restaurant_menu,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Pork Ramen',
    kcal: 480,
    desc: 'Rich, broth-based Japanese soup',
    icon: Icons.ramen_dining,
    type: 'afternoon',
  ),
  FoodRecommendation(
    name: 'Beetroot Hummus Wrap',
    kcal: 360,
    desc: 'Vibrant, nutritious vegan wrap',
    icon: Icons.eco,
    type: 'afternoon',
  ),


  // --- EXISTING EVENING FOODS (071-075) ---
  FoodRecommendation(
    name: 'Steamed Fish',
    kcal: 360,
    desc: 'Light dinner with omega-3',
    icon: Icons.set_meal,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Veg Stir Fry',
    kcal: 300,
    desc: 'Low-calorie vegetable mix',
    icon: Icons.soup_kitchen,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Grilled Salmon',
    kcal: 420,
    desc: 'Rich in protein and omega-3',
    icon: Icons.local_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Chickpea Curry',
    kcal: 370,
    desc: 'Plant protein with spices',
    icon: Icons.restaurant_menu,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Cauliflower Rice Bowl',
    kcal: 260,
    desc: 'Low-carb alternative for dinner',
    icon: Icons.rice_bowl,
    type: 'evening',
  ),

  // --- NEW EVENING FOODS (076-110) ---
  FoodRecommendation(
    name: 'Baked Sweet Potato w/ Chili',
    kcal: 450,
    desc: 'High fiber and satisfying',
    icon: Icons.local_fire_department,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Margherita Pizza (2 slices)',
    kcal: 480,
    desc: 'Classic Italian, cheese and tomato',
    icon: Icons.local_pizza,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Tuna Steak',
    kcal: 390,
    desc: 'Lean, high-protein fish',
    icon: Icons.set_meal,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Beef Tenderloin (small)',
    kcal: 410,
    desc: 'Premium cut of lean beef',
    icon: Icons.dinner_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Linguine with Clams',
    kcal: 460,
    desc: 'Italian seafood pasta',
    icon: Icons.ramen_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Roast Chicken & Asparagus',
    kcal: 400,
    desc: 'Simple, balanced protein and veg',
    icon: Icons.dinner_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Vegetable Lasagna',
    kcal: 430,
    desc: 'Cheesy, filling vegetarian bake',
    icon: Icons.set_meal,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Turkey Meatloaf',
    kcal: 380,
    desc: 'Leaner comfort food',
    icon: Icons.dinner_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Mushroom Risotto',
    kcal: 470,
    desc: 'Creamy, rich Italian rice dish',
    icon: Icons.rice_bowl,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Lamb Kebab',
    kcal: 440,
    desc: 'Grilled meat on a skewer',
    icon: Icons.local_bar,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Goulash',
    kcal: 510,
    desc: 'Hungarian beef and paprika stew',
    icon: Icons.soup_kitchen,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Cod with Roasted Veggies',
    kcal: 340,
    desc: 'Very lean white fish dinner',
    icon: Icons.set_meal,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Spaghetti Carbonara',
    kcal: 550,
    desc: 'High-fat, rich pasta dish',
    icon: Icons.ramen_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Black Cod with Miso',
    kcal: 480,
    desc: 'Japanese glazed fish delicacy',
    icon: Icons.local_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Taco Platter (3 Tacos)',
    kcal: 530,
    desc: 'Mexican street food favorite',
    icon: Icons.local_bar,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Eggplant Parmesan',
    kcal: 420,
    desc: 'Italian vegetarian comfort food',
    icon: Icons.set_meal,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Chili Con Carne',
    kcal: 400,
    desc: 'Spicy meat and bean stew',
    icon: Icons.local_fire_department,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Sizzling Fajitas (Chicken)',
    kcal: 490,
    desc: 'High-protein, customizable dish',
    icon: Icons.dinner_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Chicken Cacciatore',
    kcal: 410,
    desc: 'Hunter\'s style chicken stew',
    icon: Icons.soup_kitchen,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Seafood Paella',
    kcal: 470,
    desc: 'Spanish rice with various seafood',
    icon: Icons.rice_bowl,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Spinach and Ricotta Cannelloni',
    kcal: 450,
    desc: 'Creamy filled pasta tubes',
    icon: Icons.ramen_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Grilled Portobello Mushroom',
    kcal: 300,
    desc: 'Meaty vegetarian alternative',
    icon: Icons.eco,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Beef Stroganoff',
    kcal: 560,
    desc: 'Rich, creamy Russian dish',
    icon: Icons.dinner_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Vegetarian Pot Roast',
    kcal: 390,
    desc: 'Hearty slow-cooked vegetables',
    icon: Icons.soup_kitchen,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Jambalaya',
    kcal: 520,
    desc: 'Spicy Louisiana rice dish',
    icon: Icons.rice_bowl,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Bangers and Mash',
    kcal: 480,
    desc: 'Sausages and mashed potatoes',
    icon: Icons.dinner_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Chicken Korma (with Naan)',
    kcal: 530,
    desc: 'Mild Indian curry and bread',
    icon: Icons.restaurant_menu,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Dahl (Lentil Soup)',
    kcal: 330,
    desc: 'Indian comfort food, high protein',
    icon: Icons.rice_bowl,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Pork Belly (Crispy)',
    kcal: 600,
    desc: 'Very high fat, savory option',
    icon: Icons.dinner_dining,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Veggie Burger on Brioche Bun',
    kcal: 400,
    desc: 'Sweet bread and plant patty',
    icon: Icons.fastfood,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Enchiladas (Cheese)',
    kcal: 470,
    desc: 'Rolled tortillas with sauce and cheese',
    icon: Icons.local_bar,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Thai Green Curry',
    kcal: 430,
    desc: 'Aromatic coconut milk curry',
    icon: Icons.restaurant_menu,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Fish and Chips',
    kcal: 550,
    desc: 'Classic fried comfort meal',
    icon: Icons.fastfood,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Couscous with Veggies',
    kcal: 350,
    desc: 'Light North African grain meal',
    icon: Icons.set_meal,
    type: 'evening',
  ),
  FoodRecommendation(
    name: 'Osso Buco',
    kcal: 540,
    desc: 'Braised veal shanks, rich and heavy',
    icon: Icons.dinner_dining,
    type: 'evening',
  ),

  // --- NEW SNACK FOODS (111-140) ---
  FoodRecommendation(
    name: 'Almonds (Handful)',
    kcal: 170,
    desc: 'Healthy fats and vitamin E',
    icon: Icons.handshake,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Apple Slices & Peanut Butter',
    kcal: 230,
    desc: 'Sweet, crunchy, and protein-packed',
    icon: Icons.apple,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Carrots & Hummus',
    kcal: 150,
    desc: 'High fiber vegetable dip',
    icon: Icons.grass,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Protein Bar',
    kcal: 210,
    desc: 'Convenient on-the-go protein',
    icon: Icons.bolt,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Trail Mix',
    kcal: 250,
    desc: 'Nuts, seeds, and dried fruit blend',
    icon: Icons.handshake,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Rice Cakes (2) w/ Cheese',
    kcal: 140,
    desc: 'Light and crunchy snack',
    icon: Icons.crop_square,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Popcorn (Air-Popped)',
    kcal: 100,
    desc: 'High-volume, low-calorie fiber snack',
    icon: Icons.local_movies,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Banana',
    kcal: 105,
    desc: 'Potassium and quick energy',
    icon: Icons.psychology,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Grapes',
    kcal: 70,
    desc: 'Simple, sweet hydration',
    icon: Icons.science,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Jerky (Beef or Turkey)',
    kcal: 120,
    desc: 'Chewy, low-carb protein',
    icon: Icons.pets,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Pistachios (Shelled)',
    kcal: 180,
    desc: 'Nutty snack with a healthy fat profile',
    icon: Icons.handshake,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Fig Bars (2 bars)',
    kcal: 200,
    desc: 'Sweet, soft, and satisfying',
    icon: Icons.cake,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Pretzels (Small Bag)',
    kcal: 110,
    desc: 'Salty, crunchy carb source',
    icon: Icons.fastfood,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Chocolate Milk (Low Fat)',
    kcal: 180,
    desc: 'Recovery drink with carbs and protein',
    icon: Icons.local_drink,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Edamame (Steamed)',
    kcal: 120,
    desc: 'Soy protein and fiber',
    icon: Icons.eco,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Bell Pepper Strips',
    kcal: 30,
    desc: 'Very low-calorie vitamin C',
    icon: Icons.grass,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Air Fryer Chickpeas',
    kcal: 160,
    desc: 'Crispy, crunchy protein snack',
    icon: Icons.local_fire_department,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'String Cheese',
    kcal: 80,
    desc: 'Convenient single-serving protein',
    icon: Icons.breakfast_dining,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Wasa Crackers w/ Cottage Cheese',
    kcal: 190,
    desc: 'Scandinavian crispbread and protein',
    icon: Icons.bakery_dining,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Yogurt Parfait (small)',
    kcal: 240,
    desc: 'Layered yogurt, granola, and fruit',
    icon: Icons.local_cafe,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Cereal (Dry, Small Bowl)',
    kcal: 130,
    desc: 'Quick, high-carb energy',
    icon: Icons.breakfast_dining,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Guacamole (2 tbsp) w/ Tortilla Chips',
    kcal: 220,
    desc: 'Healthy fat dip and salty chips',
    icon: Icons.local_bar,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Sun Dried Tomatoes',
    kcal: 110,
    desc: 'Chewy, flavorful veggie boost',
    icon: Icons.wb_sunny,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Energy Bites (Date/Oat)',
    kcal: 150,
    desc: 'Natural, no-bake energy boost',
    icon: Icons.bolt,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Hard Pretzel Rods (3)',
    kcal: 100,
    desc: 'Minimal fat, salty carb snack',
    icon: Icons.fastfood,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Olives (10 large)',
    kcal: 50,
    desc: 'Salty, low-calorie monounsaturated fat',
    icon: Icons.grass,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Dried Apricots (5 pieces)',
    kcal: 80,
    desc: 'Sweet, chewy, concentrated fruit',
    icon: Icons.science,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Roasted Chestnuts',
    kcal: 130,
    desc: 'Warm, earthy, low-fat nut',
    icon: Icons.local_fire_department,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Chocolate Pudding (Low Fat)',
    kcal: 150,
    desc: 'Small, sweet dessert',
    icon: Icons.cake,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Watermelon Slices',
    kcal: 40,
    desc: 'High water content, very refreshing',
    icon: Icons.science,
    type: 'snack',
  ),

  // --- ANY TIME/DESSERT FOODS (141-170) ---
  FoodRecommendation(
    name: 'Cup of Coffee (Black)',
    kcal: 2,
    desc: 'Zero-calorie energy boost',
    icon: Icons.local_cafe,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Herbal Tea (Plain)',
    kcal: 0,
    desc: 'Hydrating, relaxing beverage',
    icon: Icons.local_cafe,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Water Bottle (500ml)',
    kcal: 0,
    desc: 'Essential hydration',
    icon: Icons.water_drop,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Diet Soda (Can)',
    kcal: 0,
    desc: 'Zero-calorie fizzy drink',
    icon: Icons.local_drink,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Chicken Broth',
    kcal: 10,
    desc: 'Warming, savory liquid',
    icon: Icons.soup_kitchen,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Green Juice',
    kcal: 110,
    desc: 'Concentrated vegetables',
    icon: Icons.grass,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Gatorade/Sports Drink',
    kcal: 120,
    desc: 'Electrolytes and sugar',
    icon: Icons.sports_soccer,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Protein Yogurt Dip',
    kcal: 130,
    desc: 'Savory yogurt with herbs',
    icon: Icons.breakfast_dining,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Vanilla Ice Cream (1 scoop)',
    kcal: 150,
    desc: 'Sweet, frozen dessert',
    icon: Icons.cake,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Chocolate Chip Cookie',
    kcal: 180,
    desc: 'Chewy, sweet baked treat',
    icon: Icons.cookie,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Small Brownie',
    kcal: 220,
    desc: 'Rich, chocolate indulgence',
    icon: Icons.cake,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Small Fruit Tart',
    kcal: 250,
    desc: 'Pastry with fresh fruit',
    icon: Icons.bakery_dining,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Dark Chocolate Square',
    kcal: 60,
    desc: 'Antioxidant-rich treat',
    icon: Icons.bakery_dining,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Gelato (small cup)',
    kcal: 160,
    desc: 'Italian ice cream, dense and rich',
    icon: Icons.cake,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Tiramisu (small slice)',
    kcal: 280,
    desc: 'Coffee-flavored Italian dessert',
    icon: Icons.cake,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Cheesecake (small slice)',
    kcal: 300,
    desc: 'Creamy, indulgent dairy dessert',
    icon: Icons.pie_chart,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Cinnamon Roll',
    kcal: 350,
    desc: 'Sweet, iced breakfast pastry',
    icon: Icons.bakery_dining,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Donut (Glazed)',
    kcal: 260,
    desc: 'Classic fried sweet dough',
    icon: Icons.donut_large,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Rice Pudding',
    kcal: 200,
    desc: 'Sweet rice-based comfort food',
    icon: Icons.rice_bowl,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Popsicle (Fruit)',
    kcal: 60,
    desc: 'Light, frozen fruit treat',
    icon: Icons.science,
    type: 'dessert',
  ),
  FoodRecommendation(
    name: 'Hot Cocoa (w/ Milk)',
    kcal: 200,
    desc: 'Warm, chocolatey beverage',
    icon: Icons.local_drink,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Sparkling Water (Flavored)',
    kcal: 5,
    desc: 'Bubbly, zero-sugar refreshment',
    icon: Icons.local_drink,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Lemonade (Sweetened)',
    kcal: 150,
    desc: 'Classic sweet and tart drink',
    icon: Icons.local_drink,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Espresso Shot',
    kcal: 1,
    desc: 'Highly concentrated coffee',
    icon: Icons.local_cafe,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Hard Candy (2 pieces)',
    kcal: 40,
    desc: 'Small, simple sugar boost',
    icon: Icons.cake,
    type: 'snack',
  ),
  FoodRecommendation(
    name: 'Iced Tea (Unsweetened)',
    kcal: 2,
    desc: 'Refreshing, plain beverage',
    icon: Icons.local_drink,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Chicken Noodle Soup (Canned)',
    kcal: 180,
    desc: 'Quick, easy, and salty meal',
    icon: Icons.soup_kitchen,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Fruit Smoothie (Dairy-Free)',
    kcal: 170,
    desc: 'Blended fruit and water/juice',
    icon: Icons.local_drink,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Garlic Bread (1 slice)',
    kcal: 180,
    desc: 'Buttery, savory bread side',
    icon: Icons.bakery_dining,
    type: 'any',
  ),
  FoodRecommendation(
    name: 'Baked Potato (Plain)',
    kcal: 160,
    desc: 'Simple carbohydrate base',
    icon: Icons.dinner_dining,
    type: 'any',
  ),
];