// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCybqgit2WpUlOzwOW5gp5e7AITxhWYc9Y',
    appId: '1:873552712801:web:389b155f72d7a37e5e4620',
    messagingSenderId: '873552712801',
    projectId: 'fitwiseapp-4c568',
    authDomain: 'fitwiseapp-4c568.firebaseapp.com',
    storageBucket: 'fitwiseapp-4c568.firebasestorage.app',
    measurementId: 'G-94JFDL5TBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz3fsLfMwyV9PrK-T4k26zoLsxbVtAnkQ',
    appId: '1:873552712801:android:63631f2395c4724f5e4620',
    messagingSenderId: '873552712801',
    projectId: 'fitwiseapp-4c568',
    storageBucket: 'fitwiseapp-4c568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM45nOw6mkWORXJNAhOON2FGRgGrOFEvU',
    appId: '1:873552712801:ios:bd478d7b480f67315e4620',
    messagingSenderId: '873552712801',
    projectId: 'fitwiseapp-4c568',
    storageBucket: 'fitwiseapp-4c568.firebasestorage.app',
    iosBundleId: 'com.example.fitwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM45nOw6mkWORXJNAhOON2FGRgGrOFEvU',
    appId: '1:873552712801:ios:bd478d7b480f67315e4620',
    messagingSenderId: '873552712801',
    projectId: 'fitwiseapp-4c568',
    storageBucket: 'fitwiseapp-4c568.firebasestorage.app',
    iosBundleId: 'com.example.fitwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCybqgit2WpUlOzwOW5gp5e7AITxhWYc9Y',
    appId: '1:873552712801:web:d0e2d6ffaabf42645e4620',
    messagingSenderId: '873552712801',
    projectId: 'fitwiseapp-4c568',
    authDomain: 'fitwiseapp-4c568.firebaseapp.com',
    storageBucket: 'fitwiseapp-4c568.firebasestorage.app',
    measurementId: 'G-JN7LBGLRS0',
  );
}
